### ISSUE TITLE
Reduce complexity of computing squares

### ISSUE THREAD

**Issue by maherou** [AndrewBreyen/CS317-Submissions#1]
Computing the square of a number can be done simply and does not need the pow function.  Use

```(num - mean, 2)*(num - mean, 2)```
instead of
```Math.pow(num - mean, 2);```

**Comment by AndrewBreyen** [comment]
implemented in latest, [commit 6e85a69715fc56bdddd1108722ecb84b8efed312](https://github.com/AndrewBreyen/CS317-Submissions/commit/6e85a69715fc56bdddd1108722ecb84b8efed312)
